### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Greeny3x3** [Aurilisdev/Physica#10]
**Is your feature request related to a problem? Please describe.**
Id like to haev a special block that contains radiation, so that you cant just make a Reactor out of Dirt

**Describe the solution you'd like**
New Block : "Reactor Wall/Reactor Block"

**Describe alternatives you've considered**
öm 

**If your feature is a new block or item please give some example(s) for names**
well...
     ***Please give some way of creating this item/block***
Lead steel lead 
Lead steel lead 
Lead steel lead 
(Bars of course ) and that Would make like 3 or so reactor blocks

**Additional context**
I think it would be enough if this block uses the standard Iron Block texture, i wouldnt go out of my way just to make a texture just for an building block

**Comment by Breadabix** [comment]
This is a nice idea, maybe along with this the three different types of concrete could be added.
