### ISSUE TITLE
Electrodynamics and it’s dependencies causing crash on initialization

### ISSUE THREAD

**Issue by McSquizzleswag** [Aurilisdev/Physica#102]
I'm using the latest versions of Electrodynamics and it's dependent mods, for 1.16.5, and it never makes it past the early mod loading window

**Comment by aurilisdev** [comment]
I need more than this in order to actually judge anything about ur problem. Can me send me ur logs?

**Comment by McSquizzleswag** [comment]
I'll be able to give the logs later today

**Comment by McSquizzleswag** [comment]
The latest log (https://1drv.ms/u/s!AnuEBEgNOmTrkCjIQysd8bACJ5rw)
And the crash report created at the time I tried launching the game (https://1drv.ms/t/s!AnuEBEgNOmTrkCttJbznlI7Q4gsE)

**Comment by aurilisdev** [comment]
I will close this for now as i dont see how this is related with electro to be honest. The crash log doesnt tell me anything about electro...

**Comment by McSquizzleswag** [comment]
I ain't giving up on this yet, the crash only ever happens with the latest version of Electrodynamics, on my test pack I dropped this mod and the other 4 down a few versions and it actually lets the game get further

**Comment by McSquizzleswag** [comment]
Do any of the 5 mods want a newer version of forge on the latest version of the mods

**Comment by McSquizzleswag** [comment]
This has everything to do with your mod, the crash only ever happens with the latest version of Electrodynamics, the developer of Reliquary says this too
