### ISSUE TITLE
[1.18] Mineral Crusher outputs the input slot

### ISSUE THREAD

**Issue by ghost** [Aurilisdev/Physica#115]
A hopper pulls from the input slot instead of the output slot.
In other words, when I put in raw iron, the hopper below pulls out the raw iron instead of the impure iron dust.

Using version 0.5.2-0

**Comment by aurilisdev** [comment]
Ur version is outdated. This will not be fixed in 1.18 and is only fixed in 1.18.1 and will only stay fixed on this version or future versions
