### ISSUE TITLE
[1.18.1] Game crashes on loading when used with Iron Furnaces

### ISSUE THREAD

**Issue by Selmephren** [Aurilisdev/Physica#124]
Tested this with:
Forge 39.0.8
Electrodynamics-1.18.1-0.5.4-0
ironfurnaces-1.18.1-3.1.1
and nothing else.

Still having that error on loading the game with just these two mods:

_The game crashed whilst initializing game
Error: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
Exit Code: -1_

[crash-2021-12-26_20.06.57-client.txt](https://github.com/aurilisdev/Electrodynamics/files/7778027/crash-2021-12-26_20.06.57-client.txt)

**Comment by aurilisdev** [comment]
I don't see why electro has anything to do with this crash

**Comment by Selmephren** [comment]
Well, there is some mod interaction between the only 2 mods loaded that is causing it to crash.

**Comment by Selmephren** [comment]
From the Iron Forge page:

> When checking for NBT data, it was assumed that only the "settings" data would be on the Furnace Settings Copier item, Electrodynamics seems to have added some NBT data on load and since as soon as there is NBT data on the item the values of the settings would be displayed, and since there was no settings present --> that is what causes the crash.
This is now fixed in 3.1.2.
Qelifern/IronFurnaces/issues/78

So it looks like they were able to track down the problem from their end.  I don't know from what end of the interaction the problem was created but now you have something to possibly point at for future errors of this kind.
