### ISSUE TITLE
Reinforced Alloyer causing crashes

### ISSUE THREAD

**Issue by GeorgeousGingerGeorge** [Aurilisdev/Physica#131]
Ticking block entity crash coming from Reinforced Alloyer when placed. Crash report below!
[crash-2022-01-07_09.00.37-server.txt](https://github.com/aurilisdev/Electrodynamics/files/7829221/crash-2022-01-07_09.00.37-server.txt)

**Comment by aurilisdev** [comment]
Has been fixed
