### ISSUE TITLE
1.18.1 dangerous overwrite mixin breaking mods 

### ISSUE THREAD

**Issue by TelepathicGrunt** [Aurilisdev/Physica#139]
I’m on mobile right now but someone came to me on my discord mentioning that in the latest update for your mod, it is now crashing my Repurposed Structures mod by making my mixin fail to apply. i took a quick look into your mod’s source to see how my mixin was breaking and yeah. 
https://github.com/aurilisdev/Electrodynamics/blob/1.18.1/src/main/java/electrodynamics/compatibility/mixin/MixinLakeFeature.java

please please do not user overwrite mixins. They are extremely dangerous and will blow up other people trying to mixin or asm into the code. Instead, it looks like you’re trying to place your own sulfur blocks in lava lakes. I would highly suggest using inject mixins for that or making your own lake feature, register it as a new feature, create the configuredfeature and placedfeature forms, and use BiomeLoadingEvent to add it to biomes. But again, please do not overwrite.

feel free to ask me if you get stuck or reach out on this discord’s mod help channels to get assistance: https://discord.mcmoddev.com/

Good luck and hope this helps!

**Comment by aurilisdev** [comment]
As i replied on discord i really didnt have the time to fully learn mixin when it was only for that one file and method. Thanks for helping :D I did realize that the mixin would be dangerous but werent sure if overriding the method would stop others doing stuff to it as i copied the vanilla source code and added some if statements :)
