### ISSUE TITLE
[1.18.1] Chunk fails to save and crashes

### ISSUE THREAD

**Issue by ArchieBeepBoop** [Aurilisdev/Physica#148]
This caused an irreversible save corruption to an existing world where an entire chunk was deleted.
https://pastebin.com/XPuZLsHm

I assume this is due to a method that was broken and subsequently removed in the latest version of forge, according to their changelog.
https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.1-39.0.45/forge-1.18.1-39.0.45-changelog.txt

**Comment by aurilisdev** [comment]
Thanks for notifying me. Will be fixed in the next update
