### ISSUE TITLE
Gears are missing the generic #forge:gears tag

### ISSUE THREAD

**Issue by lerokko** [Aurilisdev/Physica#155]
The gear items only have the material specific sub tags. For TinkersConstruct for example the casting recipe uses the material specific sub tag to create the gear, however molding the gear cast itself can be done with any generic #forge:gears.

I added this file to remedy the issue:
_forge\tags\items\gears.json_
```
{
  "replace": false,
  "values": [
    "#forge:gears/bronze",
    "#forge:gears/copper",
    "#forge:gears/iron",
    "#forge:gears/steel",
    "#forge:gears/tin"
  ]
}
```

**Comment by aurilisdev** [comment]
Added this now :)
