### ISSUE TITLE
Hunting down change log

### ISSUE THREAD

**Issue by itsdinkd** [Aurilisdev/Physica#160]
Please change the link in your curseforge change log from the website, to your github issues. Hunting down change logs while needing to update dozens of other mods for modpacks is not fun / takes time out

**Comment by aurilisdev** [comment]
I dont have the time to write a full changelog for every update so this will most likely not happen. Doing a proper system for changelogs is not gonna happen yet

**Comment by itsdinkd** [comment]
No need to write down change logs. I was recommending changing the link that is in the Curseforge Changelog section, from your website, to the repo's commit page, like you do for your other mods.

**Comment by itsdinkd** [comment]
Or not. not sure how its hard to replace
https://aurilis.dev/
with
**"https://github.com/aurilisdev/Electrodynamics/issues"**
