### ISSUE TITLE
Electrodynamics crashing on startup

### ISSUE THREAD

**Issue by YarinQuapi** [Aurilisdev/Physica#162]
Minecraft version: 1.16.5
Mod version: 0.5.0-2
Forge version: 36.2.26

Issue:
Electrodynamics crashing on startup (NuclearScience addon is present)
[crash-2022-03-05_12.16.36-client.txt](https://github.com/aurilisdev/Electrodynamics/files/8190449/crash-2022-03-05_12.16.36-client.txt)

Although there is a lot of Refined Storage in this crash report, I can assure you, without electrodynamics and nuclear science it does not crash. Also tried removing just Nuclear Science and running it with just Electrodynamics, it still crashes.

**Comment by aurilisdev** [comment]
This is known about and has been fixed for newer versions of minecraft. 1.16.5 is not supported anymore for these mods :/
