### ISSUE TITLE
Mixin failure at startup

### ISSUE THREAD

**Issue by border999** [Aurilisdev/Physica#166]
Version: Electrodynamics-1.18.1-0.6.2-3
latest log: [latest.log](https://github.com/aurilisdev/Electrodynamics/files/8436316/latest.log)

**Comment by aurilisdev** [comment]
U are trying to use electrodynamics for 1.18.1 in ur mc version 1.18.2. These are not compatible

**Comment by border999** [comment]
It's so normal for modders to just make blanket compatibility for versions like 1.18 and 1.12 that I forget it's not a default thing. Any plans to update to 1.18.2?
