### ISSUE TITLE
Block tags vs item tags

### ISSUE THREAD

**Issue by rileyg98** [Aurilisdev/Physica#168]
I've noticed that things like Mekanism's Digital Miner and other mods don't seem to be able to pick Electrodynamics ores up and it appears this is due to you only applying item tags to the ores as opposed to block tags as well (for forge:ores and the like).

**Comment by aurilisdev** [comment]
Which version are u on?

**Comment by aurilisdev** [comment]
@rileyg98 ?

**Comment by rileyg98** [comment]
Oh! I'm so sorry, i sent an email reply but it didn't work. 

Apologies: I thought I'd selected the correct branch to lodge this on - Electrodynamics-1.16.5-0.5.0-2 is the jar version.

**Comment by aurilisdev** [comment]
Ah, i see. Well i'm sorry riley but 1.16.5 isnt supported anymore :(

**Comment by rileyg98** [comment]
Apologies: I thought I'd selected the correct branch to lodge this on
- Electrodynamics-1.16.5-0.5.0-2 is the jar version.
