### ISSUE TITLE
Block GUIs bug out when far from spawn

### ISSUE THREAD

**Issue by ttttdoy** [Aurilisdev/Physica#174]
I don't exactly know how to explain this but when using a machine while being very far from spawn causes it's gui to not work properly.

Minecraft Version: 1.18.2

Example of the gui being broken
![NtTv54Q](https://user-images.githubusercontent.com/10857148/164943656-79a66210-0990-4cf8-857d-f5201e8e3f45.png)

Another example is machines the process items don't show the progress arrow being filled up.

So far i tested about 10k blocks from spawn and it didn't break, but i don't exactly know the distance at which it stops working

Steps to reproduce
1. Teleport far from spawn (I was about 80k blocks out)
2. Place a machine and view it's gui
3. Find out it's broken

Machines still function properly, just their guis are bugged.

**Comment by ttttdoy** [comment]
Complely forgot to put that this is running in 1.18.2

**Comment by aurilisdev** [comment]
Will look into this

**Comment by nia-e** [comment]
Tested as well w/ ED as part of Ampz 3.0-3, couldn't reproduce the issue. Tested 80k and 160k blocks out as per screenshots:
![image](https://user-images.githubusercontent.com/12896469/165557750-c418de60-fdbb-4539-9862-dbcb8cbc3563.png)
![image](https://user-images.githubusercontent.com/12896469/165557806-b5ab8ee4-49e4-4239-8c24-b7d19a7ed5f3.png)
