### ISSUE TITLE
server crash - ticking entity - electrodynamics damage player. i dunno.. im lost lol

### ISSUE THREAD

**Issue by TheRanker** [Aurilisdev/Physica#176]
having a crash using all your mods + lots more. making a custom modpack with some extra progressions. so indeed this may be a mod conflict. 

but i gotta start somewhere. so heres the crash.

https://pastebin.ubuntu.com/p/kdHGc7cSr9/

my modpack contains 302 mods atm.  so any details you may be able to help me resolve the issue be great. 
also have a spark report showing entity AI being very high load on server
net.minecraft.world.entity.Mob.aiStep()33.18%
https://spark.lucko.me/gRSsWAvf0i

strange that the ai is mentioned in the crash. only reason i mentioned the spark report here.  otherwise id have no clue where the ai is being called from. haha

any additinal tests you need me to do try and do , ill gladly do it. im developing this modpack for curseforge. heres the link
https://www.curseforge.com/minecraft/modpacks/nuclear-explo-r-sion

**Comment by aurilisdev** [comment]
Your entity AI load has nothing to do with my mods. However, the crash will be fixed :)

**Comment by TheRanker** [comment]
Awesome thanks for the ai tip. I have a few suspects ;) keep up the great work!!

**Comment by K-Fitzpatrick** [comment]
Also getting this crash during `electrodynamics.common.event.PlayerHandler.compareArmor`.
Originally made an issue over at https://github.com/baileyholl/Ars-Nouveau/issues/520 (see that for full logs)

**Comment by AlexiyOrlov** [comment]
May be related: https://github.com/AlexiyOrlov/k-turrets/issues/1
