### ISSUE TITLE
What file handles quarry logic?

### ISSUE THREAD

**Issue by Wdfitzpat007** [Aurilisdev/Physica#177]
Really appreciate what you are trying to do, reviving old minecraft modpacks.

There is so little information about this mod. The quarry seems to act a little like a buildcraft quarry except it is a multi-block machine and requires things that are not intuitive. I assume that the absence of tutorial is not out of sadism but lack of time. Send me the logic behind the quarries and I can figure out how it works and maybe make a video tutorial if you are feeling confident about keeping it the way it is.

Alternatively you could tell me what I am doing wrong, but I know you likely have no time for that.

[
![QuarryIssue](https://user-images.githubusercontent.com/48187056/168683482-e1b7b65e-1297-4997-9e97-c262bc636b21.PNG)
](url)
![QuarryThings](https://user-images.githubusercontent.com/48187056/168683648-68ada997-15d1-44bf-a466-22bcca7e4f46.png)

**Comment by aurilisdev** [comment]
Sorry about a slow answer. I have been in my exam period for 2 weeks and im not done for another 2. I will start working again when im done with this!
