### ISSUE TITLE
Recipe not showing in Just Enough Items

### ISSUE THREAD

**Issue by YongAn404** [Aurilisdev/Physica#178]
The items in your project failed to display the synthesis formula in JEI in 1.18.2, how can I solve it?

你的项目中物品未能在1.18.2中的JEI显示合成配方，请问我该如何解决？

**Comment by YongAn404** [comment]
![image](https://user-images.githubusercontent.com/101850798/170225514-a6a0368d-f181-43b8-805b-768006d21fb2.png)

**Comment by YongAn404** [comment]
I would like to add some questions. I have not found any relevant Modular Force Field System tutorials on the Chinese Internet, and the Wiki you provided has not found any official tutorials about Modular Force Field System. Where is your official tutorial?

我想追加一些问题，我并没有在中国互联网上找到相关Modular Force Field System教程,你们提供的Wiki也没有查到关于Modular Force Field System的官方教程，请问你们的官方教程在哪？

**Comment by aurilisdev** [comment]
I have no official tutorial for these mods however they all work like their old versions from voltz
