### ISSUE TITLE
Vanilla recipe conflict: Iron Trapdoor and Iron Plate

### ISSUE THREAD

**Issue by SheriffEllis** [Aurilisdev/Physica#179]
![image](https://user-images.githubusercontent.com/22532064/171968729-bddb7452-5174-4d4b-a04f-53952fa1ecd9.png)
![image](https://user-images.githubusercontent.com/22532064/171968740-5f3e6df3-99e7-4ce0-8f77-9bb32b924a2b.png)

Forge Version: 40.1.25
Mod Version: 1.18.2-0.6.3-10

**Comment by aurilisdev** [comment]
Will fix this

**Comment by darkphan** [comment]
Is this going to get fixed? It is still like this in 0.10.1-6 for Minecraft 1.21.1.
