### ISSUE TITLE
About a serious bug in Electrodynamics 1.16.5

### ISSUE THREAD

**Issue by michaelng1129** [Aurilisdev/Physica#181]
![image](https://user-images.githubusercontent.com/43681657/174448995-20ff47e2-4aeb-479b-be32-1c439012e3e1.png)
it will add a NBT tag to all item, And then all of item will not stack if you throw it and pick up it.
Some of another mod such as RefinedStorage disk drive will cuase a problem as the disk cant not put into the disk drive because of this bug.

**Comment by aurilisdev** [comment]
Electrodynamics 1.16.5 is no longer supported
