### ISSUE TITLE
[1.18.2 -1.18.1] Incompatibility Electrodynamics & create craft & addition

### ISSUE THREAD

**Issue by BlackEagle73** [Aurilisdev/Physica#187]
**Describe the bug**
Bug between electrodynamics mod and create addition. when you use the mixer of electrodymics we can't use canister to take them. when we disable create craft and additions the bug disapeard 

**To Reproduce**
Use sulfuric acid in chemical mixer with raw fluorite crystal.
Put canister to take back the result (hydofluoric acid.

**Additional context**
Crate:
- Mod version: 20220817a
- Forge version: 40.1.69
- Create version: 0.5.0d
Electrodynamics:
Mods version :0.6.4-0
Nuclear Science:
Mod version : 0.4.8-11

**Comment by BlackEagle73** [comment]
[crash-2022-08-20_10.39.22-fml.txt](https://github.com/aurilisdev/Electrodynamics/files/9387191/crash-2022-08-20_10.39.22-fml.txt)
[crash-2022-08-20_10.46.49-client.txt](https://github.com/aurilisdev/Electrodynamics/files/9387192/crash-2022-08-20_10.46.49-client.txt)

**Comment by tbvns1** [comment]
I have the same issue.
