### ISSUE TITLE
How to close update

### ISSUE THREAD

**Issue by xiakkto** [Aurilisdev/Physica#189]
I want to turn off update, how do I do that please (1.16.5)

**Comment by aurilisdev** [comment]
I dont know what you mean by this?

**Comment by xiakkto** [comment]
![AI)OH74`{5$%{`M~RTPTF1Z](https://user-images.githubusercontent.com/109633750/194027303-4d7d5387-b679-4d26-b193-a27f1b368d88.png)
This makes the tps of my game very low
