### ISSUE TITLE
 64x64 partial Accelerator that is not passing 82% velocity

### ISSUE THREAD

**Issue by Toe-NaiL** [Aurilisdev/Physica#19]
this is a 64x64 partial Accelerator that is not passing 82% velocity
 and I'm not sure why. Does it really need to be bigger? 

![partical](https://user-images.githubusercontent.com/53271263/62665281-acd7fd00-b94c-11e9-810d-5119f090e5c6.jpg)

![62631726-2c3edf80-b8ff-11e9-82eb-a46d3bb52e85](https://user-images.githubusercontent.com/53271263/62709306-1b57a200-b9c3-11e9-869a-b679c903f745.png)

**Comment by aurilisdev** [comment]
Are you playing on the voidflame server?

**Comment by Toe-NaiL** [comment]
Private server we are testing out the modpack on. I guess one thing I'm wondering is if there is a way to increase the power usage to increase the speed.

**Comment by aurilisdev** [comment]
No. The version of Physica on VCM is outdated alot so it would require a backport for me to update it. I will talk to kmecpp about this. If you have any further questions please pm me on discord: aurilisdev#4673
