### ISSUE TITLE
Question regarding the translation of the Guidebook

### ISSUE THREAD

**Issue by SxKILL** [Aurilisdev/Physica#190]
Sorry, I don't know exactly where to ask this question. How can the Guidebook be translated? I tried opening class files with InClassTranslator, but instead of text I get guidebook.electrodynamics.chapter.gettingstarted.p1l1. I take it this is some kind of page reference? Then where can I find these pages?

Sorry to bother you.

**Comment by aurilisdev** [comment]
Should all be in the normal en_us lang file
