### ISSUE TITLE
[Bug] Sulfide/Sulfur Ore Gen

### ISSUE THREAD

**Issue by Tellik** [Aurilisdev/Physica#191]
Electrodynamics:oresulfur is not following ore gen rules.

`S:default=tin:silver:lead:uraninite:thorianite:monazite:vanadinite:sulfur:niter:aluminum:chromite:rutile:halite:lepidolite:molybdenum:fluorite:sylvite -> oresToSpawn='tin:silver:lead:uraninite:thorianite:monazite:vanadinite:sulfur:niter:aluminum:chromite:rutile:halite:lepidolite:molybdenum:fluorite:sylvite'
D:default=1.0 -> OREGENERATIONMULTIPLIER='0.0'`

The rest of the ores seem to be behaving correctly.

From looking at the code, it looks like sulfur generates separately from the oregen, even though sulfur is identified in the ores to spawn.

**Comment by aurilisdev** [comment]
Fixed it now for 1.19.2 :)

**Comment by Tellik** [comment]
Any chance of it getting updated for 1.18 as well?
