### ISSUE TITLE
[1.19.2][0.7.0-4] Mineral Washer not outputting resulting solution into the canister

### ISSUE THREAD

**Issue by Zarvera** [Aurilisdev/Physica#192]
As per title. There're 2 slots in the GUI for canisters, JEI shows canisters in both usually - one for input, other for the output. The output one doesn't seem to work - i'm sitting with the washer full of lithium sulfate unable to get it out.

**Comment by aurilisdev** [comment]
Will look into this

**Comment by aurilisdev** [comment]
Should be working now. If not make a new issue with the newest version
