### ISSUE TITLE
Ore Spawn Configs not working.

### ISSUE THREAD

**Issue by Lewimaron** [Aurilisdev/Physica#193]
Hi,

I'm trying to disable a few ores from this mod but the config doesn't seem to be having any effect in game when creating a new world. I'm not sure if the configs are supposed to be copied from the defaultconfigs folder to the serverconfigs folder in each world save like other mods configs, but they're not moving across.

Here are my config files just in case I'm doing something wrong.
[electrodynamics.txt](https://github.com/aurilisdev/Electrodynamics/files/10240308/electrodynamics.txt)
[electrodynamics_ore_config.txt](https://github.com/aurilisdev/Electrodynamics/files/10240309/electrodynamics_ore_config.txt)

**Comment by aurilisdev** [comment]
This has been fixed.
