### ISSUE TITLE
Crash with Forge 40.1.0/1.18.2

### ISSUE THREAD

**Issue by TheDoctor1977** [Aurilisdev/Physica#194]
Log: https://mclo.gs/AtpEta4

Occurs on launch, unsure what could have caused it because of how many mods are in this pack, the Electrodynamics addons I'm using are Dynamic Electricity and Modular Force Fields Systems

**Comment by RGBRedGreenBlue** [comment]
I have had the same issue on Forge 40.1.60 except I'm using it with Balistix

log: https://mclo.gs/U75rFd4

It also gives the same error when running by itself

**Comment by aurilisdev** [comment]
Update your forge and electrodynamics version
