### ISSUE TITLE
CTD making new world

### ISSUE THREAD

**Issue by festro** [Aurilisdev/Physica#199]
When loading into world generation it will crash to MineCraft launcher giving me this error

The game crashed whilst mouseclicked event handler
Error: java.lang.UnsupportedOperationException: You must include an operating tick time!

[crash-2023-02-13_18.30.34-client.txt](https://github.com/aurilisdev/Electrodynamics/files/10728113/crash-2023-02-13_18.30.34-client.txt)

**Comment by aurilisdev** [comment]
Is this a new world or one you had generated a month ago or more?

**Comment by festro** [comment]
it's a new world, that screen that pops up after clicking singleplayer when you have no worlds. I don't even get to the screen where where I set it up.
It goes in this order, after I click "singleplayer" it displays "preparing for world creation", about a second later it displays "saving", then crashes.

**Comment by aurilisdev** [comment]
Try updating all of my mods

**Comment by festro** [comment]
Will do when it shows up on curseforge.
