### ISSUE TITLE
Cannot transfer uranium hexafluoride

### ISSUE THREAD

**Issue by NeonIsFading** [Aurilisdev/Physica#20]
I am having trouble transferring the uranium hexafluoride out of the chemical boiler and into the gas centrifuge.

Both Thermal Dynamics and Mekanism pipes don't work and I can't find any help online.

**Comment by jtljac** [comment]
Have you tried setting mekanism mechanical pipes to extract with the configurator?

**Comment by aurilisdev** [comment]
You need to shift right click on the connection between the Mekanism pipes and the machines with a configurator to make them pull out fluids.

**Comment by NeonIsFading** [comment]
> 
> 
> You need to shift right click on the connection between the Mekanism pipes and the machines with a configurator to make them pull out fluids.

Thank you it works! This was so frustrating to figure out. Thank you for the reply
