### ISSUE TITLE
Fermentation Plant doesn't work in 1.19.2

### ISSUE THREAD

**Issue by willis1030** [Aurilisdev/Physica#206]
I found Fermentation Plant some times do not work. I have check that power is 120v, water and power is enough.
It is work in version 1.18.2 with the same situation
Another bug is that water input at the yellow side, not blue. (The user guide said blue is the input side.)

forge1.19.2-43.2.6
electrodynamics-1.19.2-0.7.1-4

**Comment by aurilisdev** [comment]
Water input works fine for me. Power also works fine. Probably you that dont have enough power or something like that.
