### ISSUE TITLE
Build a Quarry, leave and re-enter the server, it crashed.

### ISSUE THREAD

**Issue by willis1030** [Aurilisdev/Physica#208]
I have test this for 3 times. recreate server, build a quarry, leave the game and re-enter the server, then I can't enter the server.
my client side crashed, not the serverside. but if I stop the server and restart, sometimes it start success, sometimes failed.
No one can enter the server again!

![image](https://user-images.githubusercontent.com/16789564/222852258-979a8767-6b36-4532-ae8f-bc6e5547061b.png)

![image](https://user-images.githubusercontent.com/16789564/222852362-cba9c9db-d3c9-49cc-9de9-9af5a32baf46.png)

forge1.19.2-43.2.6
Electrodynamics-1.19.2-0.7.1-4

I will do more test, if there is new discover, I would report here.

**Comment by willis1030** [comment]
Infact, the only one machine "quarry" make the crash happen.
I removed all the other mods but Electrodynamics, create a single player game, put a quarry machine on the ground, leave the game then re-enter it, crash happened.

![image](https://user-images.githubusercontent.com/16789564/222857201-645a365e-922b-44eb-8d0a-e9f9def24bc0.png)

**Comment by aurilisdev** [comment]
Can you provide the crash log?

**Comment by willis1030** [comment]
I have paste the logs in Discord. bugs-sendlogs. but some one told me it fixed.
Thank you for fix it.

**Comment by willis1030** [comment]
The latest version fixed this, thank you!

**Comment by FranzFischer78** [comment]
The issue came up again. Posted a log in the discord
