### ISSUE TITLE
The left page of the user guide covered with jei records

### ISSUE THREAD

**Issue by willis1030** [Aurilisdev/Physica#209]
I download the 3 mods of latest version, and found that user guides in language file are easier to translate than before, it's good job!
but new guide has a little problem like this:

https://user-images.githubusercontent.com/16789564/223705911-eb9eb13f-559f-4fc6-a523-e441b74e799c.mp4

forge1.19.2-43.2.6
Electrodynamics-1.19.2-0.7.2-0
Nuclear+Science-1.19.2-0.5.2-0
Ballistix-1.19.2-0.6.3-0

**Comment by skiprocks999** [comment]
This has been fixed.
