### ISSUE TITLE
Some ore blocks haven't processing recipes 

### ISSUE THREAD

**Issue by tabr** [Aurilisdev/Physica#210]
1. <item:electrodynamics:orehalite>
2. <item:electrodynamics:oremonazite>
3. <item:electrodynamics:orethorianite>
4. <item:electrodynamics:deepslateoreuraninite>
5. <item:electrodynamics:orefluorite>
If get them with silk touch. The only way to process them is destroy block and get raw ores.

**Comment by skiprocks999** [comment]
Monazite is processed in MFFS directly in ore form. The others have been added as requested.
