### ISSUE TITLE
Sulfuric acid multiplication

### ISSUE THREAD

**Issue by tabr** [Aurilisdev/Physica#214]
[Sulfur trioxide] + 1000mb water => 2500mb [Sulfuric acid]
1000mb [Sulfuric acid] + ore => 1000mb [ore sulfate]
1000mb [ore sulfate] => 5shards
1shard => [dust] + 19%chance [sulfur trioxide]
Now we have 19*5=95% chance of [sulfur trioxide] and... 1500mb of [Sulfuric acid]
Bug?
Should be 1000mb [Sulfuric acid]? Or even smaller value?

**Comment by aurilisdev** [comment]
Fixed
