### ISSUE TITLE
Getting CTD on world creation

### ISSUE THREAD

**Issue by festro** [Aurilisdev/Physica#216]
After updating to Electrodynamics-1.19.2-0.7.2-3.jar I still seem to be getting the same issue
here's the log 
[crash-2023-03-25_19.55.15-client.txt](https://github.com/aurilisdev/Electrodynamics/files/11070645/crash-2023-03-25_19.55.15-client.txt)

**Comment by festro** [comment]
after the last update the error seems to have jumped to something else
here's the log.
[crash-2023-03-26_15.19.26-client.txt](https://github.com/aurilisdev/Electrodynamics/files/11073212/crash-2023-03-26_15.19.26-client.txt)

**Comment by skiprocks999** [comment]
It's an issue with jaopca. They need to update their JSON syntaxes. Report it to the mod author.
