### ISSUE TITLE
crash at version 1.19.2-0.7.2-4

### ISSUE THREAD

**Issue by tabr** [Aurilisdev/Physica#219]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

https://pastebin.com/uPhJmN4N

**Comment by skiprocks999** [comment]
Are you doing something with custom recipes?

**Comment by tabr** [comment]
> Are you doing something with custom recipes?

yep. but with prev version all ok.

**Comment by skiprocks999** [comment]
The fluid tag you are using does not have any fluids associated with it, hence the crash

**Comment by tabr** [comment]
ok. Anyway I've stop using this mod.

**Comment by skiprocks999** [comment]
Bud you are supplying an empty fluid tag to the recipe. You either need to define the fluid tag with your custom recipes or use a pre-defined one. I know the recipe system very well (as I wrote it) and this is exactly what you're doing.

**Comment by tabr** [comment]
the recipes i've added:
https://pastebin.com/5zaLDaTW

**Comment by skiprocks999** [comment]
Ah I see your issue. It's in you Electrolytic Separator recipe. You have the input "tag": "electrodynamics:fluidethanol"

All of our fluid tags can be found here: 
https://github.com/skiprocks999/Electrodynamics-Fork/tree/1.19.2/src/generated/resources/data/forge/tags/fluids

Also just for reference, I know at least in 1.16.5 Electrodynamics Ethanol and Sulfuric Acid were compatible with other mod's versions of those fluids, so you shouldn't need those recipes for the most part.

If you still have crashes after fixing that however, let me know, as I am by no means a perfect coder :D

**Comment by tabr** [comment]
emm... https://github.com/skiprocks999/Electrodynamics-Fork/blob/1.19.2/src/generated/resources/data/forge/tags/fluids/ethanol.json

{
  "values": [
    "electrodynamics:fluidethanol"
  ]
}
This 'data" recipe that i copied from your data. Also mod works(but don't remember if recipe works) at version [1.19.2-0.7.2-3] but crush at [1.19.2-0.7.2-4].(https://github.com/aurilisdev/Electrodynamics/issues/219#top)

**Comment by tabr** [comment]
I've stop use this mod because i making a big modpack(120+ mods). And this mod is in alpha version. There is many things that would be(and should be) reworked.
If all this messages in make no sense... please forgive me waste your time.

**Comment by skiprocks999** [comment]
That's not how tags work. The value that you reference is the name of the tag file. In this case it would be forge:ethanol. The value you are referencing is the fluid from electrodynamics.

**Comment by skiprocks999** [comment]
If you are going to say stuff needs to be reworked, you have to list some specific points. We are not going to swap to FE if that is one of the items.

**Comment by tabr** [comment]
I'm not talking about "swap to FE". I've even think to change other mods to use your electricity.
The machines and tools need to be finished. Tools is useledd because need to be charged too often. Potrable battery pack should help.
For now use your machines is uncomfortable. In ic2 this is well done - you can place "transformer upgrade" to machines so you can use one high voltage to all machines. In this mod i can't do this.
The upgrades is very bad design(IC2 design). If i need to pull from left and push right there would be 1 upg slot left. IUs it would be exp upg? Or transformer? Or? The better way, i think, in Meksnism(awesome, i think) and Thermal - inside machine you can select which side is in and what is out.
What is going on with Electricity killing? Sometimes it just kills. Any defence? Near transformer or solar panel with insulated wires. Why kills? WHy not damage as in ImmersiveEngeneering?
Sometime to one machines pipes(wires) should be connected to all of it's sides. very ugly. Multiblock machines, i think, would be awesome in this case.
About electricity - there would be nice if i can to multiplicate voltage to any value, not just this 3. Anyway you can calculate current to check when wire should explode. You can limit max voltage on transformers - where voltage is over the limit - it will explode, because of breakdown of coil insulation.
The mod is in alpha version i think. It is many things need to be finished to make it Beta, then RC and finally release.
This mod i've installed because of NuclearScience - but there is too simple for me. Awesome idea with vaporating directly water blocks but there would be awesome if i get a steam and then make power from this steam and this steam i want to be processed back to water. In IC2 this done in better way i think.

**Comment by skiprocks999** [comment]
I think it's important to note a couple things first. Electrodynamics is designed to be realistic. As a result, we have made certain design choices that, while might be more difficult from a gameplay perspective, have parity with real life. Electro also uses a modular design philosophy, with a base mod that has machines and base mechanics, and then add-on mods to expand on those aspects. 

1. Electricity is dangerous. You don't want to touch an exposed wire in real life because it will kill you. Same principle applies.
2. We can look at having a battery pack of some sorts and increasing battery life. If you have a recommended increase please suggest it.
3. Machines having a required voltage is a challenge. It's the same challenge that you experience in the real world. 
4. You can transform voltage to any value you want. We have to standardize on certain values however, otherwise it's impossible to predict when trying to design a system. There are standard voltage ratios in the real world too
5. Upgrades have limited slots. IC2 has the same mechanic. If you want to focus on automation, install Assembly Line.

We are working on expanding mechanics to flesh out ideas, however this takes time. To say electro is a beta or alpha mod is not fair and very insulting. Using the standard of "things should be rebalanced, this mod is not release" would place every mod in beta or alpha.

**Comment by tabr** [comment]
> I think it's important to note a couple things first. Electrodynamics is designed to be realistic. As a result, we have made certain design choices that, while might be more difficult from a gameplay perspective, have parity with real life. Electro also uses a modular design philosophy, with a base mod that has machines and base mechanics, and then add-on mods to expand on those aspects.
> 
> 1. Electricity is dangerous. You don't want to touch an exposed wire in real life because it will kill you. Same principle applies.
> 2. We can look at having a battery pack of some sorts and increasing battery life. If you have a recommended increase please suggest it.
> 3. Machines having a required voltage is a challenge. It's the same challenge that you experience in the real world.
> 4. You can transform voltage to any value you want. We have to standardize on certain values however, otherwise it's impossible to predict when trying to design a system. There are standard voltage ratios in the real world too
> 5. Upgrades have limited slots. IC2 has the same mechanic. If you want to focus on automation, install Assembly Line.
> 
> We are working on expanding mechanics to flesh out ideas, however this takes time. To say electro is a beta or alpha mod is not fair and very insulting. Using the standard of "things should be rebalanced, this mod is not release" would place every mod in beta or alpha.

1. The highest voltage with i work was 1200v. I know WHAT electricity is. The behavior is not intuitive(i think this is bug). One more time: SOMETIMES it kill. The better implementation is in mod Immersive Engeneering. Try it.
2. See Thermal series - there is capacitor. Can charge all of energy sfaff from any mod. Awesome i think.
3. In real life i can't put ingredients into machine and get product from other side. And if i can - 100% it would use one voltage. Another example: there is mass devices that use 5v, 12v, 24, 48, 3.3 and even 1000v dc... And all of them use... 220/110v. Think about it.
4. in RL a can make 3 bus with different voltage and connect any machine to own voltage. Here a can't do this. To resolve this you can use wires like in ImmersiveEngeneering.
5. IC2 is bad design i think. I have belts from Create, IE. And don't think i need another one(IE belts looks better). Also i use AE2 mod - it is many automation work.
You work is great! Thanks for that you are doing!
But anyway there is too much work to make it to state where i can have a fun while playing your mod.
Hope this talks is helpful.

**Comment by skiprocks999** [comment]
1. If there is a bug with the electrocution please report it and it will be investigated. We need more than "it doesn't work" however, as we do need to try to reproduce it ourselves or at least need to have something specific to investigate. The highest voltage I work with is 138kV if we want to play that game as well.
2. I have a concept for "recharging" I need to bounce off Aurilis, however it's nothing like a battery pack.
3.  Electro is inherently an AC mod. Yes battery boxes are a fudge, but you can imagine the rectifier and inverter built in.
4. AC machines need very specific voltages and frequencies to run. Yes speed upgrades fudge that, however you can imagine the them adding an additional motor. Having to juggle multiple voltages is also part of the challenge. 
5. I have considered a round-robin mode for multi-slot machines.

There are problems that we recognize and are working on solutions for, however it takes time to implement them.

**Comment by tabr** [comment]
1. Ok. When will install it again.
2. Your tools have "charge capacity"... so it have some battery inside...
3. Any PC power supply(inside PC) works like this: a) AC (HV)=> DC(hV) => DC(LV - 12v) => DC (5v,3.3v, -3.3v,...) And this supply easily can be 1kw and would be small. There is no problem to make AC from DC. True-sin would be only with motor. But off-line UPS use "Modified sine wave". It is cheap and small. Useful for applications
4. Yes and AC motors (mostly) to change it's rotation speed need to be changed frequency of current.
5. will see=)
To implement true-AC voltage need to 2/4 wires (zero+Line/3 lines). Inductivity. Air breakdown. Ground. Transformers should work a little bit in a different way.
I talking about this because anyway you would use simplification and it is good if you have clean vision of things that should be done and another things what should be simplified. :)
