### ISSUE TITLE
I cannot open the game because the mod crash. 

### ISSUE THREAD

**Issue by RobbieYep** [Aurilisdev/Physica#222]
I am playing at 1.19.2 with Forge 43.2.8
My version of Electrodynamics mod is 0.7.2-4
I tried with Modular Forcefield's versions 0.1.2-0, 0.1.1-0, 0.1.0-2 but every case is the same crash.
Help me, please :(
Here is the log from aternos but in my personal minecraft is the same case:
https://mclo.gs/dut1l5t

**Comment by aurilisdev** [comment]
Has been fixed
