### ISSUE TITLE
Wire mill allows getting "free" ingots of another type

### ISSUE THREAD

**Issue by jesserockz** [Aurilisdev/Physica#225]
We recently had a server and I had put some superconductive ingots in the wire mill.
After those had been finished, I took out the wire, but left the nuggets in.
I then put in copper ingots and the machine worked away creating copper wire and adding +1 to the superconductive nugget count, allowing me to have "free" superconductive nuggets.

**Comment by aurilisdev** [comment]
I see. Will work on this

**Comment by aurilisdev** [comment]
Fixed.
