### ISSUE TITLE
Powering and activating forcefield in 1.20.1 | I need help!!!

### ISSUE THREAD

**Issue by Smansun** [Aurilisdev/Physica#230]
Can't find out how to power my forcefield. No tutorial covers the 1.20.1 version and the only help I can find is through the FTB wiki which says I need to have Industrial Craft or any similar mods, but they are all outdated. I have the required dependencies but I can't find out how they work together. Is there any hidden tutorial or guide for MFFS 1.20.1 or is it a lost cause? The mod seems fire, hope somebody can guide me through the mod. (I have searched online but every tutorial and picture is outdated.
![image](https://github.com/aurilisdev/Electrodynamics/assets/150598140/ff829216-fbe4-4662-908f-ccdf16fc77be)

**Comment by aurilisdev** [comment]
Come in the electro discord and u can get help!
