### ISSUE TITLE
mod loading error (1.20.1)

### ISSUE THREAD

**Issue by festro** [Aurilisdev/Physica#232]
following the update to electrodynamics (0.9.0-1) game fails to load giving these logs
[crash-2023-11-18_11.03.31-fml.txt](https://github.com/aurilisdev/Electrodynamics/files/13401262/crash-2023-11-18_11.03.31-fml.txt)
[latest.log](https://github.com/aurilisdev/Electrodynamics/files/13401263/latest.log)

**Comment by agentwolf88** [comment]
same

**Comment by skiprocks999** [comment]
your version of MFFS is outdated. Also check if other dependent mods are outdated.

**Comment by skiprocks999** [comment]
no response, considered fixed
