### ISSUE TITLE
Latest update has issues serverside with what I can assume is "fowarding" old blocks

### ISSUE THREAD

**Issue by MatchTerm** [Aurilisdev/Physica#233]
Hello,

Updated recently the sets of 4 mods (ED,NS,Ballistix and DE) in my modpack, and server side it just constatly crashes with the following log.
[crash-2023-11-19_15.23.33-server.txt](https://github.com/aurilisdev/Electrodynamics/files/13403667/crash-2023-11-19_15.23.33-server.txt)
Log file also has the modlist of the server.

**Comment by skiprocks999** [comment]
This has been fixed and will be out with the next update

**Comment by MatchTerm** [comment]
Thank you!
