### ISSUE TITLE
Unkown Crash that happens randomly after a while in server

### ISSUE THREAD

**Issue by guivnf** [Aurilisdev/Physica#234]
[crash-2023-11-20_19.12.00-server.txt](https://github.com/aurilisdev/Electrodynamics/files/13419947/crash-2023-11-20_19.12.00-server.txt)

Had a crash that basically made my friends unable to join the server. I've tried to remove all of the mods mentioned on the crash reports.
Idk how to reproduce this crash, but the crash report should be enough to get what happened.

**Comment by skiprocks999** [comment]
This has been fixed and will be out with the next update

**Comment by guivnf** [comment]
> This has been fixed and will be out with the next update

I'm guessing this was fixed on 9.0.2 right?

**Comment by skiprocks999** [comment]
Yes
