### ISSUE TITLE
[1.19.2] Some mod tanks create infinite fluid inside Electrodynamic machines

### ISSUE THREAD

**Issue by Saereth** [Aurilisdev/Physica#235]
basically this is a pnuematicraft fluid tank but some other modded tanks work as well. The combustion generator/dc motor will fill its internal buffer without actually consuming any liquid from the tanks. 

https://user-images.githubusercontent.com/26591/284781929-1565922b-e826-4ec9-9a4c-32d462d3ed8e.png

Originaly reported here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4306

**Comment by skiprocks999** [comment]
send me the json for the fuel type and I'll see if I can replicate it in the new update we're working on.

**Comment by Saereth** [comment]
well the lubricant one where it's happening is completely stock electrodynamics json recipe but the lpg fuel is this:

[lpg.json](https://github.com/aurilisdev/Electrodynamics/files/13444852/lpg.json)

**Comment by DiggityMan420** [comment]
happens with crude oil too

**Comment by skiprocks999** [comment]
This has been fixed and will be out with the next update

**Comment by skiprocks999** [comment]
The update with the fix has been released
