### ISSUE TITLE
Inaccurate analogy for Volts and Amps in guidebook

### ISSUE THREAD

**Issue by tobfal** [Aurilisdev/Physica#236]
I've been fascinated by this mod as it is brining a rather realistic interpretation of electricity into the game. Although I noticed an inaccuracy in the use explanation of voltage and current.
The guidebook says `The speed of the flow is measured in units of Volts, which are denoted with a capital V. The volume of the flow is measured in units of Amperes (Amps for short), and is denoted with a capital I or A.`, which is a bit confusing. Let me explain. You are using the so-called hydraulic analogy for electricity. In this analogy, voltage is not represented by the speed of the flow, but the difference in pressure. The current on the other hand is the flow rate, the volume of liquid over time.

So a more accurate analogy would be for example: `The speed of the flow is measured in units of Volts, which are denoted with a capital V. This represents the electric potential or voltage, analogous to the pressure in a fluid system. The volume of the flow is measured in units of Amperes (Amps for short), denoted with a capital I or A. This represents the electric current, analogous to the flow rate of a fluid.`

**Comment by skiprocks999** [comment]
This will be corrected with the update to 1.20.4

**Comment by aurilisdev** [comment]
^^
