### ISSUE TITLE
Fortune upgrade for the electric drill not working in Electrodynamics

### ISSUE THREAD

**Issue by Kluuless** [Aurilisdev/Physica#240]
Adding the fortune upgrade to electric drills in Electrodynamics appears to enchant it with fortune, as expected, but then upon breaking various ores, no extra drops were yielded. I tested this on redstone ore, broke a few without upgrades and with fortune 3, they yielded about the same amount of redstone. Then I tried it on raw gold ore with the fortune upgrade, and never got more than 1 raw gold.

**Comment by aurilisdev** [comment]
Will look into this'

**Comment by skiprocks999** [comment]
Fixed and will be out with next update
