### ISSUE TITLE
I can't disable oregen in 1.19.2

### ISSUE THREAD

**Issue by coco875** [Aurilisdev/Physica#242]
I try to disable oregen with this config:
[electrodynamics.txt](https://github.com/aurilisdev/Electrodynamics/files/13635480/electrodynamics.txt)
[electrodynamics_ore_config.txt](https://github.com/aurilisdev/Electrodynamics/files/13635481/electrodynamics_ore_config.txt)
![image](https://github.com/aurilisdev/Electrodynamics/assets/59367621/24291e19-37fc-4f93-8a25-b4271a5f0f4e)
but doesn't work.

**Comment by skiprocks999** [comment]
A bugfix patch will be released soon revamping this config. Please inform us if this still is a problem.

**Comment by coco875** [comment]
> A bugfix patch will be released soon revamping this config. Please inform us if this still is a problem.

I try your PR but when I launch the game it's crash with ballistix so I assume he need also you version fix of ballistix but I can't get compiled

**Comment by coco875** [comment]
there is a way to get all early build to test ?

**Comment by coco875** [comment]
and I try your pr and effectivly any ore spawn except sulfur who continue to spawn in place like here
![image](https://github.com/aurilisdev/Electrodynamics/assets/59367621/646f0106-4e31-4a53-bfa0-fb1b4fd23140)

**Comment by skiprocks999** [comment]
I need to see your config file

**Comment by coco875** [comment]
I don't change the config file since the last time

**Comment by coco875** [comment]
https://github.com/aurilisdev/Electrodynamics/files/13635480/electrodynamics.txt

https://github.com/aurilisdev/Electrodynamics/files/13635481/electrodynamics_ore_config.txt

**Comment by skiprocks999** [comment]
The config file is vastly different in the update. You have not built the correct item.

**Comment by coco875** [comment]
ok by setting just OREGENERATIONMULTIPLIER to 0 it's work

**Comment by skiprocks999** [comment]
The update is released. You should be able to disable ores properly now. Please inform us if it still does not work

**Comment by coco875** [comment]
it work thanks
