### ISSUE TITLE
Suggestion: Guide

### ISSUE THREAD

**Issue by CTH999** [Aurilisdev/Physica#25]
In my opinion, it would be nice if there was a guide in-game, that gives you info on any of the modules instield (I.E. The Modular Force Field section is only there if it's downloaded)

However, that is just an idea. Ultimatly, it is your mod.

Also, out of curiosity, why is the core up to 1.16, but all the other mods only up to 1.7.10?

**Comment by aurilisdev** [comment]
The core is up to 1.16 cause i started updating it a couple days before you sent this message xD. Sorry for the slow reply. The other mods will be updated as well!

**Comment by CTH999** [comment]
> The core is up to 1.16 cause i started updating it a couple days before you sent this message xD. Sorry for the slow reply. The other mods will be updated as well!

Great! Thanks! (Also, no problem for the slow reply, sorry for my slow reply to yours, since I started checking this slower (:
