### ISSUE TITLE
Failure to create/load worlds with JAOPCA and Electrodynamics

### ISSUE THREAD

**Issue by Xebakyr** [Aurilisdev/Physica#250]
Minecraft version: 1.18.2
Forge version: 40.2.17
JAOPCA version: 4.1.16.34 (latest for 1.18.2)
Electrodynamics version: 0.6.5-0 (latest for 1.18.2)

Currently making a 1.18.2 pack using JAOPCA with a bunch of tech mods. Whenever I try to create a world, I get an error telling me that "Errors in currently selected datapacks prevented the world from loading".

I've done a binary search and to get my mod list down to where I can pretty confidently say that the issue is between JAOPCA and Electrodynamics, as these are the only two "content" mods I have left in the pack. Removing either fixes the issue and world creation can proceed as normal. I'm not sure if the issue is on JAOPCA or Electrodynamics side, but I saw a similar issue made here on JAOPCAs side

https://github.com/TheLMiffy1111/JAOPCA/issues/277

Log: https://gist.github.com/Xebakyr/f0e4887a983c9cab47db8528693bc574

**Comment by skiprocks999** [comment]
They will need to update their JSON syntax for 1.18.2. We backported our modern recipe system with the last update. I knew they had support for us in 1.19.2; I didn't realize they had support for us for 1.18.2 or I would have informed the author.
