### ISSUE TITLE
[Electro Dynamics - 1.20.1 - 0.9.0-3] Coal Cannot be Shift-Clicked into Furnaces as Fuel

### ISSUE THREAD

**Issue by Dandelion1608** [Aurilisdev/Physica#254]
In Vanilla MC, Shft Clicking fuels like Coal/Charcoal will move them to the fuel slot by default, with Electrodynamics installed they now shift click into the Ore slot and will not Shift Click into fuel slot even when the top slot is full

Minor Inconvieniance as it can still be moved manually into the fuel slot

**Comment by aurilisdev** [comment]
Wait i never thought this was electro's fault :O

**Comment by skiprocks999** [comment]
This is because Electrodynamics adds a recipe for smelting coal. Big Reactors/Extreme Reactors does the same thing.
