### ISSUE TITLE
[ED Suite (EDVers:1.20.1-0.9.0-3)] Monazite Ore Appears to have no uses

### ISSUE THREAD

**Issue by Dandelion1608** [Aurilisdev/Physica#255]
Monazite or drops an ore block that appears in NEI to have no processing uses and no further information in the EEC Guidebook beyond the location details of the Ore Generation

Using the entire suite of mods less Assembly

- Electrodynamics 1.20.1-0.9.0-3
- Blastcraft 1.20.1-0.4.0-2
- Nuclear Science 1.20.1-0.6.0-2
- Dynamic Electricity 1.20.1-1.1.0-1
- Ballistix 1.20.1-0.7.0-3
- Modular Forcefields 1.20.1-0.2.0-1

**Comment by aurilisdev** [comment]
Yup Monazite ore has no uses atm
