### ISSUE TITLE
[Electro Dynamics - 1.19.2 - 0.8.1-1] (FTB Genesis) Seems like Wires can't properly convert energy.

### ISSUE THREAD

**Issue by ArtpokeBr** [Aurilisdev/Physica#258]
![ed_converting_bug](https://github.com/aurilisdev/Electrodynamics/assets/44851727/84338418-6a1b-46e4-a73f-b5027cea421c)
After some testing, this is the only way to properly convert energy, connecting blocks directly.

**Comment by manmaed** [comment]
Just for tracking on ftb issue tracker:  https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5202

**Comment by aurilisdev** [comment]
WIll see if i can do something about this

**Comment by skiprocks999** [comment]
This is an issue with Industrial Reborn and not Electrodynamics. I had this same problem while trying to get it to work in Dynamic Electricity. Short of trying to update Industrial Reborn there is not much we can do here on our end.
