### ISSUE TITLE
Weird behavior with battery boxes in creative mode

### ISSUE THREAD

**Issue by DoctorSnakes** [Aurilisdev/Physica#266]
Battery box shows wrong numbers after doing these steps:

1. Be in creative mode
2. Fill up a battery box with some power
3. Make sure your inventory is empty, and then middle mouse click on the battery box so it appears in your hand
4. Place the battery box, and right click it

Once you look inside the battery box, it says it has 0 joules. However, once you connect a wire to it, it changes its number.

**Comment by skiprocks999** [comment]
This will be fixed with the next update

**Comment by skiprocks999** [comment]
After further research the fix here can't be justified for 1.20.1 due to what needs to be changed to fix the bug. It will be patched in 1.21.
