### ISSUE TITLE
[ed 0.9.1-0 for 1.20.1] Memory Leak probably?

### ISSUE THREAD

**Issue by asamufaja** [Aurilisdev/Physica#267]
I'm not sure how to prove it, but I've been experiencing a memory leak and after looking around quite a bit it seems like it's from generating any power and putting it through a wire. 
Memory gets used up faster when there are more amps going. A single coal generator is very minimal. With three fission reactors going, I went through 15gb of RAM in something like four hours.
I'm getting the memory usage by looking at the top right of the f3 info and seeing just a little more ram usage every time the JVM GC cleans things up. I just leave it sitting with the factory not doing much and check every 10 mins or so, no loading chunks or much of anything else.
I do have quite a few other mods, but I've narrowed it down to just electrodynamics/nuclear science generating power and sending it down a wire. Not a noticeable memory leak if generators are running, but no wires involved.

This crash report specifically points to the transformer block causing issues
[crash-2024-07-28_17.14.08-server.txt](https://github.com/user-attachments/files/16431817/crash-2024-07-28_17.14.08-server.txt)

There's probably a few more memory issues in my list of mods (found in the crash report), but this is the biggest one by a lot.

**Comment by skiprocks999** [comment]
This will be addressed in the next update.
