### ISSUE TITLE
Circuit Monitor bug in v1.20.1

### ISSUE THREAD

**Issue by AsianMan888** [Aurilisdev/Physica#271]
Let's say I set the value at 50A and change the operator to "greater than" for a 360A rating copper wire. If anything exceeds 50A, it would send out a redstone signal and open the circuit via relay. Now you would assume that anything under 50A the circuit would continue to stay closed and still work. It does not! For some reason no matter what I set the value at, it constantly sends out a redstone signal even though it's way under the set value.

Later I figured out that the circuit monitor was fixated on the ampacity of the wire and not the actual amps that are going through it when machines and what not are being used. I figured that out by just putting the value 360A or higher but that wouldn't matter because the wire would've melted by the time the circuit monitor could even detect the amp being greater than whatever.
This goes for all the wires, even the wire that has inf amount of amps

**Comment by skiprocks999** [comment]
The issue here is that you are trying to use Ampacity to monitor the active current over the wire. The device would need a "Network Current" option to monitor what you want to. That being said I can add that feature for 1.21.

**Comment by skiprocks999** [comment]
Upon further review, the functionality you seek is already in the game. You can find the current from the Wattage on the circuit, which you are provided.

**Comment by AsianMan888** [comment]
> Upon further review, the functionality you seek is already in the game. You can find the current from the Wattage on the circuit, which you are provided.

My brain isn't braining, I haven't played in a while. Mind showing me an example?

**Comment by skiprocks999** [comment]
You can find the current from the wattage.

**Comment by AsianMan888** [comment]
> You can find the current from the wattage.

Oh, okay. I misread at the time. I've been playing since that reply so I think I've got it under control now, thanks.
