### ISSUE TITLE
Drill mining speed bonuses below 200% do not count

### ISSUE THREAD

**Issue by jsburger** [Aurilisdev/Physica#278]
The caluclation for drill mining speed uses the following formula;
> baseSpeed * max(1, (headSpeed * upgradeSpeed) / 2)

I assume this was intended to make the over-all speed scaling halved. But this implementation leaves smaller bonuses like Stainless Steel drill heads useless, as 1.25/2 = .75, which gets nullified by the max operation. If the halving is still desired, a formula like this could be used instead:
> baseSpeed * (1 + ((headSpeed * upgradeSpeed) - 1) / 2)

This correctly reduces percentage bonues by half. +25% => +12.5%. Of note, this new formula does adjust the speed bonuses upward. Previously a +300% (x4) speed bonus would grant +100% (x2) speed, and with this formula it will grant +150% (x2.5) speed.

Alternatively, to avoid hiding numbers behind the speed bonuses granted to the drill, it could be rebalanced and the division removed. As I understand it, the base mining speed of the drill is already quite high, so bonuses quickly get out of hand.

**Comment by skiprocks999** [comment]
The simplest option here is just to remove the / 2.0. Not sure why that's there tbh.
