### ISSUE TITLE
Thermoelectric Generator has half of intended output

### ISSUE THREAD

**Issue by jsburger** [Aurilisdev/Physica#279]
As described, Thermoelectric Generators only output about 250W. I checked the code and it is multiplying the power output by
> fluidLevel/16

The maximum level of lava is only 8, so this halves the total output.

**Comment by skiprocks999** [comment]
It is possible the fluid level amount changed since this was written. I will look into it.

**Comment by skiprocks999** [comment]
You are correct that is a static value. I will adjust it.
