### ISSUE TITLE
Insane performance drops with electrodynamics insulated wires

### ISSUE THREAD

**Issue by AndrewEllen** [Aurilisdev/Physica#288]
Electrodynamics-1.20.1-0.9.1-0

Regular insulated wires are causing a huge drop in frames. It gets worse the closer you get to the wires and looking through a grid of 8-16 wires tightly packed drops frames as low as 30-40 fps regardless of pc hardware.

Hardware tested:
R5 5600 + RTX 3060ti
R7 7800X3D + RTX 4080
R7 7600 + RTX 4070 Super

**Comment by skiprocks999** [comment]
I cannot replicate this issue and I have a significantly weaker graphics card and processor. If you are running performance mods that makes it impossible for me to find any kind of issue.

![2024-10-25_16 05 13](https://github.com/user-attachments/assets/99de0c47-3070-4cef-b067-482cf15c3e39)
