### ISSUE TITLE
Incompatiblity with Modular Powersuits

### ISSUE THREAD

**Issue by xstmass** [Aurilisdev/Physica#33]
Tested version - 1.7.10 
Link - https://www.curseforge.com/minecraft/mc-mods/modular-powersuits

Just not started and have crash-report: https://www.pastery.net/rxnxyn/
And have another one crash-report: https://www.pastery.net/mfsswv/

Starting without this mod - work fine. Conflicting only with Modular Powersuits.

**Comment by xstmass** [comment]
I found some strange. If put all files from ModularPowersuits.jar to PhysicaCore,jar - all start normally and work without errors. Maybe that help with solve this problem.
@aurilisdev help)

**Comment by aurilisdev** [comment]
As 1.7.10 isnt supported and i have only seen this error with you and i know for a fact that other modpacks use modular powersuits with physica without this issue i wont look too deeply into it as the error is extremely weird but i will look back into this error if i get more issues with this :)
