### ISSUE TITLE
Force Fields using too much fortron?

### ISSUE THREAD

**Issue by DarkShadow44** [Aurilisdev/Physica#34]
I'm using 1.7.10 and your force field mod.
Is it normal that even medium forcefields (radius 4 blocks) use so much fortran that one needs multiple Coercion Drivers to feed them? It doesn't seem to scale well. Big forcefields would need hundreds of Coercion Drivers.
I also tried speed upgrades, but even a full stack (= very expensive) does barely double the fortron produced.

Am I doing something wrong here, or is this how it is supposed to be?

Regards,
DarkShadow44

**Comment by aurilisdev** [comment]
Add three stacks of speed upgrades and it would work :)

**Comment by DarkShadow44** [comment]
Alright, if that's how it's supposed to be. Thanks for the quick answer (and the great mod :))!
