### ISSUE TITLE
[1.16.3] Copper doesn't ore dictionary with other mods

### ISSUE THREAD

**Issue by ProsperCraft** [Aurilisdev/Physica#36]
You can only use copper from Electrodynamics for Electrodynamics.

Electrodynamics-1.16.3-0.1.9-1

**Comment by burshaz** [comment]
I'm also looking into how to add the ores and ingot their respect odedict categories. Both item and block tags.
I.E.
forge:ores
forge:ores/copper
forge:ingots
forge:ingots/copper

**Comment by aurilisdev** [comment]
They will be added in the future.
