### ISSUE TITLE
jei-1.16.3-7.3.2.36 	Electrodynamics-1.16.3-0.1.9-1  Missing and invalid recipes

### ISSUE THREAD

**Issue by litjohn50** [Aurilisdev/Physica#37]
jei-1.16.3-7.3.2.36
Items without any recipe at all:

Bronze: https://gyazo.com/222b12c34dee12df45a3058a22dd112a
Used in few machines but unable to craft them.

Mineral Crusher: https://gyazo.com/dc76ce43a46411bd8fe3999a722a96a1

Iron, Silver, Gold, Super conductor, Advanced Solar Panel : https://gyazo.com/5ce548702cc99bcc86dacd05dd1885f3

Items with incorrect recipe:

Solar panels: https://gyazo.com/e08ae26f95d651e54a608a0d38b87f19
Their being used to make plates making it uncraftable.

None of the Machine show usage in JEI to make item that pertain to the mod.

Example: https://gyazo.com/d57fa2b6fbf3dad28f32c1e562fff89b

Seems like most other items have recipes or usage as of this version.

**Comment by aurilisdev** [comment]
The wires are all made in the wire mill other than the copper wire. Bronze will be fixed in the next version and JEI support will be added in the future but not for some time
