### ISSUE TITLE
Add direct Applied Energetics Compatibility.

### ISSUE THREAD

**Issue by Oakiepal** [Aurilisdev/Physica#4]
Compatibility with AE2 is needed. This is extremely useful for automation of Physica systems in modpacks.

![image](https://user-images.githubusercontent.com/45017441/51793920-25882080-2196-11e9-890a-fa2f43674d5b.png)

- [ ] Add compatibility with AE2 cables.

**Comment by spannerman79** [comment]
You might want to hook into the TE/block of https://ae-mod.info/Energy-Acceptor/

**Comment by aurilisdev** [comment]
> You might want to hook into the TE/block of https://ae-mod.info/Energy-Acceptor/

The issues that we are just the fact that automation doesn't work

**Comment by spannerman79** [comment]
As there isn't much (actually none) documentation, no [wiki](https://github.com/Aurilisdev/Physica/wiki) etc, and as I haven't played with the mod yet it is a bit hard to suggest anything or point towards another project that uses AE2 for automation.

I know that AE2 can insert into an inventory like a chest (even if its just a single slot chest), each side of the TE can be linked to a certain slot location.  For example for a plain vanilla furnace if you insert into the side that is linked to the fuel slot. Top is items to be smelted/cooked, etc.

**Comment by aurilisdev** [comment]
Yeah i know that. The machines all work with hoppers perfectly normal and with item pipes from other mods and so on. Just not AE. I will have to do more testing though.

**Comment by Breadabix** [comment]
Ae is a big part of most packs now would be nice to be able to automate these machines with it.
