### ISSUE TITLE
Error while loading single world

### ISSUE THREAD

**Issue by Azruine** [Aurilisdev/Physica#40]
It said 
"I'm playing on Forge version 1.16.1, and only have 2 mods installed: Quark 1.16.1 and AutoRegLib 1.16.1. When I try to create a new world it gives me the pop-up "Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually."

logs: https://pastebin.pl/view/300b5c8d

**Comment by aurilisdev** [comment]
You are using electrodynamics for 1.16.4 on your 1.16.1 version. This will not work

**Comment by Azruine** [comment]
Um... I'm definitely using 1.16.4 since i've added your mod to Valhelsia 3 modpack

**Comment by aurilisdev** [comment]
Huh seems like i might have an error. But anyways you shouldnt use mods from different versions which im 100% sure you are doing anywas :) Should have a fixed version up within an hour

**Comment by Azruine** [comment]
Oh. I'm such a dumb. Just ignore the following: **"I'm playing on Forge version 1.16.1, and only have 2 mods installed: Quark 1.16.1 and AutoRegLib 1.16.1. When I try to create a new world it gives me the pop-up** 

I'm not playing 1.16.1 and that was my dumb mistake since I've copied the error message from reddit :(

The message displayed on the minecraft window was only this part: **Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually.**

you can find mods I've added in the log file.
