### ISSUE TITLE
[1.16.4] Data Pack issue on world creation

### ISSUE THREAD

**Issue by YOYOK9** [Aurilisdev/Physica#41]
It seems while I have your mod in my modpack it is unable to create a single player world (have yet to try a server, sp tests first). From looking at my logs it gets hung up on "Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: minecraft:item:forge:plates/iron" 

I have tested both with and without Electrodynamics and it works as intended without. Also booting into safe mode fails / doesn't load either. 

MC: 1.16.4
Forge: 35.1.13
Electrodynamics: 1.16.4-0.1.10-1
Error message: https://puu.sh/GYTWq/75ed95a083.png 
Log:  https://gist.github.com/YOYOK9/9198782e59ce155295ab77f8df250eb5

Edit: I am downloading through the curse launcher. Oddly it shows 2 versions of the mod with the same name. I have tried both and gotten the same outcome: https://puu.sh/GYUaP/65be706302.png

**Comment by aurilisdev** [comment]
This is being fixed :)
