### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Miradae** [Aurilisdev/Physica#48]
My pack crashes on start with:
java.lang.NoClassDefFoundError: physica/nuclear/common/block/BlockElectromagnet

Log Attached for possible mod conflicts
[latest.log](https://github.com/aurilisdev/Electrodynamics/files/5927856/latest.log)

**Comment by aurilisdev** [comment]
The forcefield mod requires the nuclear physics mod for some of its recipes :) Thats why it doesnt load. You dont have the nuclear physics mod installed.

**Comment by Miradae** [comment]
I've added the nuclear physics mod, now i get the following crash:
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: physica/api/core/IContent

I've installed the mod via curseforge, so I thought it would also download all dependencies with it (it installed electrodynamics automatically), probl nuclear physics is missing in the dependency list of curseforge.

Logfile attached
[latest.log](https://github.com/aurilisdev/Electrodynamics/files/5927993/latest.log)

**Comment by Miradae** [comment]
I checked the files again and noticed that despite clicking install in curseforge, it downloaded a very old version of nuclear physics (something 0.x.x beta). I had to manually select a new version, there seems to be something of with the curseforge settings.
After installing the newest version of nuclear physics, the pack started without issues

**Comment by aurilisdev** [comment]
Nice :D Glad the problem is fixed 👍🏻
