### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by IceflowRE** [Aurilisdev/Physica#51]
> The user of this is subject to the newest version of this license.

Is a huge problem.
It allows you to change the license on your and **only** your behalve. (e.g. You could write pay me 20€ and it would be fine, because the user automatically updates from an old license to the new one, even if he uses an old picese of software from you and never saw the new license.)
In some countries (if not all)/ jurisdiction this license would be even invalid. As it must be possible to opt out to new licenses/ agreements, as uniliteral changes to contracts are forbidden by law.

**Comment by aurilisdev** [comment]
Yes and i will look into it :)
