### ISSUE TITLE
How Do I Turn Down the Oregen?

### ISSUE THREAD

**Issue by aminecraftplayerx** [Aurilisdev/Physica#58]
Hi. Thanks for the mod, I'm really looking forward to using it and Nuclear Science.

But how do I reduce or eliminate your ore generation? I can't dig into a rock without finding copper, tin, and lead from this mod. It seems like you're trying to follow real life a little bit with these mods, and these ores are just not that common (and they also duplicate a bunch of other mods gen'ing the same thing).

Thanks for your time.

**Comment by aurilisdev** [comment]
You cant do this yet. Might be changed in the future
