### ISSUE TITLE
Mod not working?

### ISSUE THREAD

**Issue by nitrogenFox** [Aurilisdev/Physica#59]
I am currently trying to use your 1.7.10 mod and I haven't used github before, so forgive me if I'm doing something wrong with this message. I got the latest 1.7.10 version of Physica Modular Forcefield System and the PhysicaCore for the exact same version number, and every time I try and use it, even with it being the only mods in my mods folder, the game crashes and says something about an "Electromagnet" not being defined. I will post a crash log for you. I really don't think this is an error on my part as I know it's not conflicting with anything. Would you please check this? Thanks!
Crash report:
https://paste.ubuntu.com/p/gqD77FPNsV/

**Comment by aurilisdev** [comment]
Its because apparently i forgot to remove something that requires the nuclear science mod as well. This will be fixed, but i dont properly support 1.7 nor do i have the time to work on any version for a few weeks due to school.

**Comment by nitrogenFox** [comment]
Thanks for the help, adding nuclear science worked! No need to change anything, maybe just list nuclear science as a dependency.
