### ISSUE TITLE
Crash with AE2

### ISSUE THREAD

**Issue by brachy84** [Aurilisdev/Physica#7]
**Describe the bug**
Game crashes on startup

**To Reproduce**
1. Install Physica and Applied Energistics 2
2. Run minecraft
3. Crash

**Expected behavior**
Everything is normal without physica

**Screenshots**
-

**Additional context (crash Log)**
https://pastebin.com/jWa06bhS

**Comment by aurilisdev** [comment]
Firstly, it appears that you are running Minecraft 1.12.2. Physica is only compatible with Minecraft 1.7.10.
Secondly, If you look at the crash log Physica doesn't appear to have been loaded at all and the crash is coming from Applied Energistics only.
