### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by Ethan156** [Aurilisdev/Physica#71]
Currently, Electrodymanics ores cannot be interchangeable with other mod ores because the ores and ingots do not have the appropriate Item and/or Block tag entries (Ex: tag:items:forge:ores/copper for copper, etc.). I saw this was suggested on a separate issue and closed when it was said that it will be "added soon." That was almost a year ago, when can we expect this feature, if ever? I think it is very important in making it compatible in modpacks.

Minecraft 1.16.5
Electrodynamics 0.4.0-1
Forge 36.2.2

**Comment by aurilisdev** [comment]
This has already been implemented in the newest source code

**Comment by DariusSG** [comment]
Hey, I am using Minecraft 1.16.5, Electrodynamics 0.5.0-0, and I cannot use tinker's mechwork copper ingot in the wire mill. I does have the appropriate ore dict entries.
