### ISSUE TITLE
Unlimited Radiation

### ISSUE THREAD

**Issue by Greeny3x3** [Aurilisdev/Physica#9]
Hey, many thanks that you made this, i waited literal years for a working port (for 1.7.10) of atomic science that has all the features.
Jsut one question, is it intended that the radiation of an fission reactor emits around the whole map? i flew 1000+ blocks away and am still affected by it. Or did i build the Reactor wrong? (the Reactor is on the overworld with nothing surrounding it tho)

Hope you can help me and thanks again :D

**Comment by aurilisdev** [comment]
I'm happy to hear that :D The reactor does not actually generate any radiation yet. Are you sure you didn't have a fuel rod or anything else radioactive in your inventory?

**Comment by Greeny3x3** [comment]
Holy fuck im such an idiot yes of course i had rods in my inv xD thx again

**Comment by aurilisdev** [comment]
Np mate :D
