### ISSUE TITLE
Crash with Refined Storage

### ISSUE THREAD

**Issue by DariusSG** [Aurilisdev/Physica#97]
Upon updating to version 0.5.0, It crashed with refined storage. I am running Minecraft 1.16.5. 
I have checked and It only affects both mods Using a separate mod pack with just only these two mods. The crash report and reason for crashing are the same.

[Crash Log](https://pastebin.com/00zu9YcU)

**Comment by aurilisdev** [comment]
Nothing in this crash report tells me anything about electrodynamics? When does the crash occur?

**Comment by DariusSG** [comment]
There is the crash log for just only these two mods : 
[Log](https://pastebin.com/rJwKksy9) 
[Debug Log](https://pastebin.com/yMZZqEP1)

After testing, It still persists on every version of refined storage for 1.16.5 and only on the newest version of electrodynamics.
Applied energetics is fine though but I have not tried auto crafting. 

Sidenote
Why is Mekanism sulfuric acid not compatible even though the recipe to get them is similar? (applies to hydrogen fluoride )
The Fission Reactor core and particle injector are near impossible to automate, for on demand; always keep in stock is possible but hard and could break if I ran out of electromagnetic cells, without computercraft (CC: Tweaks) unless it is not meant to be easily automatable.

**Comment by aurilisdev** [comment]
They arent made to be easily automatable. Also mekanism gasses and fluids wont ever be compatible. Also once again that log only shows me that refined storage is crashing. Ask them why and then i might be able to fix it if its because of Electrodynamics but otherwise i can't do anything about it.

**Comment by DariusSG** [comment]
One of the maintainers/authors of refined storage says that you are loading the tooltip before the world load.

Issue link: https://github.com/refinedmods/refinedstorage/issues/3129

**Comment by aurilisdev** [comment]
Thanks for asking them :) Will look into it!

**Comment by sandalle** [comment]
Both Electrodynamics 1.16.5-0.5.0 and 0.5.0-1 cause this crash, downgrading Electrodynamics to 1.16.5-0.4.0-1 does not crash.

**Comment by aurilisdev** [comment]
Sorry 1.16 is not supported anymore

**Comment by jdawg3636** [comment]
Fixed it bois <3

**Comment by sandalle** [comment]
Hrm, still seems to crash for me with Forge 1.16.5-36.2.23, ElectroDynamics 1.16.5-0.5.0-2 (and related mods updated), and Refined Storage 1.9.16, using Java 11.0.13 64-bit on Windows 10 if it matters.

Reverting Electrodynamics (and related mods downgraded) to 1.16.5-0.4.0-1 doesn't crash.

[crash-2022-01-17_16.57.36-client.txt](https://github.com/aurilisdev/Electrodynamics/files/7885376/crash-2022-01-17_16.57.36-client.txt)
