### ISSUE TITLE
crash with both Refined Storage and Storage Network 1.16.5

### ISSUE THREAD

**Issue by redo6565** [Aurilisdev/Physica#98]
crash with both Refined Storage and Storage Network 1.16.5
[crash-2021-11-12_01.28.32-client.txt](https://github.com/aurilisdev/Electrodynamics/files/7534982/crash-2021-11-12_01.28.32-client.txt)
[crash-2021-11-13_14.26.11-client.txt](https://github.com/aurilisdev/Electrodynamics/files/7534985/crash-2021-11-13_14.26.11-client.txt)

**Comment by aurilisdev** [comment]
Duplicate
https://github.com/aurilisdev/Electrodynamics/issues/97
